### ISSUE TITLE
Unable to use `ldap` auth provider if provider name doesn't match `ldap`

### ISSUE THREAD

**Issue by chroto** [F5Networks/f5-ansible-bigip#1]
##### COMPONENT NAME

* `bigiq_as3_deploy`

##### ANSIBLE VERSION

```
ansible 2.10.8
...
  python version = 3.8.5 (default, Jan 27 2021, 15:41:15) [GCC 9.3.0]
```
##### BIGIP VERSION
do not know
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

Can not use an ldap auth provider (for example, "ldap-my.mydomain.com") to use the BigIQ API . When fetching an auth token, this Ansible module will build the url incorrectly https://github.com/F5Networks/f5-ansible-bigip/blob/devel/ansible_collections/f5networks/f5_bigip/plugins/httpapi/bigiq.py#L198-L202 

It shouldn't be using the provider name as arg `{0}` . it should be `https://localhost/mgmt/cm/system/authn/providers/ldap/<UUID>/login`

##### STEPS TO REPRODUCE

```
- name: AS3
  hosts: bigip
  connection: httpapi
  gather_facts: false

  tasks:   
    - name: Deploy or Update
      f5networks.f5_bigip.bigiq_as3_deploy:
          content: "{{ lookup('file', 'declarations/as3.json') }}"
     vars:
         f5_provider: ldap-my.mydomain.com
      tags: [ deploy ]
```

##### EXPECTED RESULTS

Playbook runs, authenticates with the BigIQ api, and deploys the AS3 declaration

##### ACTUAL RESULTS

```
 ansible.module_utils.connection.ConnectionError: Authentication process failed, server returned: {'code': 400, 'message': 'No login provider found.', 'originalRequestBody': '{"username":"XXXXXXXXX","loginReference":{"link":"https://localhost/mgmt/cm/system/authn/providers/ldap-my.mydomain.com/ac6514af-b16d-9201-aaea-60cea111daaa/login"},"generation":0,"lastUpdateMicros":0}', 'restOperationId': 162129111, 'errorStack': [], 'kind': ':resterrorresponse'}
```
