### ISSUE TITLE
Errors deploying AS3 deploys are not caught, reports success with no failure info

### ISSUE THREAD

**Issue by chroto** [F5Networks/f5-ansible-bigip#31]
##### COMPONENT NAME
Ansible module: bigiq_as3_deploy

##### ANSIBLE VERSION

```
ansible [core 2.12.3]
  config file = /opt/ansible/win/ansible.cfg
  configured module search path = ['/opt/ansible/shared/library']
  ansible python module location = /opt/venvs/ansible50/lib/python3.8/site-packages/ansible
  ansible collection location = /opt:/usr/share/ansible/collections
  executable location = /opt/venvs/ansible50/bin/ansible
  python version = 3.8.10 (default, Mar 15 2022, 12:22:08) [GCC 9.4.0]
  jinja version = 3.0.3
  libyaml = True
```
##### BIGIP VERSION

```
BIG-IP 14.1.4.5 Build 0.0.7 Point Release 5
```
##### OS / ENVIRONMENT

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.4 LTS"
##### STEPS TO REPRODUCE

1. Write a playbook that uses the `f5networks.bigiq_as3_deploy` module
2. Verify correct authentication/authorization w/ the username/password and connectivity to the bigiq target
3. write an As3 declaration for the `content` field that does not comply with the schema overlay that's being used
4. Run the playbook 

```

```

##### EXPECTED RESULTS

Task fails and prints the results to console

For example,

```
TASK FAILED =>
{'id': 'f837b0c2-b03e-4efe-8df5-45aaff82248c', 'results': [{'code': 422, 'declarationFullId': '', 'message': 'declaration is invalid according to provided schema overlay: data should NOT have additional properties'}], 'declaration': {}}
```
##### ACTUAL RESULTS

Task succeeds and playbook continues running. No error messages are displayed

```

```

**Comment by chroto** [comment]
playbook.yaml
```yaml
---
- name: Setup Loadbalancer Service
  hosts: all
  gather_facts: no
  collections:
    - f5networks.f5_bigip

  tasks:
    - name: "F5 - Deploy/Update service using AS3 declaration API"
      f5networks.f5_bigip.bigiq_as3_deploy:
        state: present
        content: "{{ lookup('template', 'templates/as3.json.j2') }}"
      register: f5_as3_deploy_request
      vars:
        ansible_user: "{{ f5_bigiq_username }}"
        ansible_httpapi_password: "{{ f5_bigiq_password }}"
        ansible_connection: httpapi
        ansible_httpapi_port: '443'
        ansible_httpapi_use_ssl: true
        ansible_httpapi_validate_certs: no
        ansible_network_os: f5networks.f5_bigip.bigiq
        ansible_host: "{{ f5_connection_bigiq_host }}"
        f5_provider: local
```

templates/as3.json.j2
```json
{
  "class": "AS3",
  "action": "deploy",
  "declaration": {
    "class": "ADC",
    "schemaVersion": "3.12.0",
    "target": { "address": "10.10.10.10" },
    "tenant-1": {
      "class": "Tenant",
      "foo_443": {
        "class": "Application",
        "schemaOverlay": "http-as3-example-v1",
        "remark": "testing",
        "pool_foo_8080": {
          "class": "Pool",
          "members": [
            {
              "hostname": "node1.example.com",
              "servicePort": 8080
            }
          ]
        },
        "Monitor": {
          "class": "Monitor",
          "send": "GET / HTTP/1.0\\r\\n\\r\\n",
          "receive": "HTTP/1.",
        },
        "Service_HTTP": {
          "class": "Service_HTTP",
          "pool": "pool_foo_8080",
          "virtualPort": 443,
          "virtualAddresses": [
            "100.100.100.101"
          ]
        }
      }
    }
  }
}
```

**Comment by mkyrc** [comment]
> 

can you send as version of ansible colletion (`ansible-galaxy collection list f5networks.f5_bigip`) and version of `f5-appsvcs`?

I had very similar question (#19)  some months ago. `f5networks.f5_bigip.bigip_as3_deploy` module response is without details. solution in my case was using 'raw' module `ansible.builtin.uri`. 



here is my task (in block):
```yaml
        - name: "{{pb_prfx}}-03-02: Deploy JSON file to device (URI)"
          ansible.builtin.uri:
            url: "https://{{ bigip_host }}:{{ provider.server_port }}/mgmt/shared/appsvcs/declare?controls.dryRun={{ansible_check_mode}}"
            method: POST
            body: "{{ lookup('file', JSON_FILE ) }}"
            headers:
              X-F5-Auth-Token: "{{ AUTH_RESULT.json.token.token }}"
            body_format: json
            status_code: [200, 202]
            timeout: 300
            return_content: true
            validate_certs: "{{ provider.validate_certs }}"
          register: DEPLOY_RESULT
          failed_when: DEPLOY_RESULT.status != 200 and DEPLOY_RESULT.status != 202
          # ignore_errors: true
          # no_log: true
          check_mode: no
          when:
            - active_member is defined
            - active_member == true
            - AUTH_RESULT.json.token.token is defined            
          tags:
            - deploy
            - deploy-debug

        - name: "{{pb_prfx}}-03-03: [OK] Deploy result"
          debug:
            msg:
              - "status:  {{ DEPLOY_RESULT.status }}"
              - "msg:     {{ DEPLOY_RESULT.msg | default('') }}"
              - "results: {{ DEPLOY_RESULT.json.results | default('') }}"
              - "id:      {{ DEPLOY_RESULT.json.id | default('') }}"
          when:
            - active_member is defined
            - active_member == true
            - DEPLOY_RESULT.status is defined
            - DEPLOY_RESULT.status == 200 or DEPLOY_RESULT.status == 202
          tags:
            - deploy-debug
            - deploy
```

when device respond is code 202 (it is switching to async mode), we need request in a loop task ID `DEPLOY_RESULT.json.id`):

```yaml
- name: "{{pb_prfx}}-03-04: Wait for async result"
          ansible.builtin.uri:
            url: "https://{{ bigip_host }}:{{ provider.server_port }}/mgmt/shared/appsvcs/task/{{DEPLOY_RESULT.json.id}}?controls.dryRun={{ansible_check_mode}}"
            method: GET
            headers:
              X-F5-Auth-Token: "{{ AUTH_RESULT.json.token.token }}"
            status_code: [200, 202]
            timeout: 300
            return_content: true
            validate_certs: "{{ provider.validate_certs }}"
          register: DEPLOY_RESULT_ASYNC
          failed_when: DEPLOY_RESULT_ASYNC.status != 200 and DEPLOY_RESULT_ASYNC.status != 202
          until: DEPLOY_RESULT_ASYNC.json.results.0.message == "success"
          retries: 5
          delay: 20
          # no_log: true
          check_mode: no
          tags:
            - deploy
            - deploy-debug
          when:
            - active_member is defined
            - active_member == true
            - DEPLOY_RESULT.status is defined 
            - DEPLOY_RESULT.status == 202
            - DEPLOY_RESULT.json.id is defined

        - name: "{{pb_prfx}}-03-05: [OK] Deploy result (after async wait)"
          debug:
            msg:
              - "status:  {{ DEPLOY_RESULT_ASYNC.status }}"
              - "msg:     {{ DEPLOY_RESULT_ASYNC.msg | default('') }}"
              - "results: {{ DEPLOY_RESULT_ASYNC.json.results | default('') }}"
              - "id:      {{ DEPLOY_RESULT_ASYNC.json.id | default('') }}"
          when:
            - active_member is defined
            - active_member == true
            - DEPLOY_RESULT_ASYNC.status is defined
            - DEPLOY_RESULT_ASYNC.status == 200
          tags:
            - deploy-debug
            - deploy
```

when response code is different to 200 or 202, rescue task shows response with more details (even more details as `f5networks.f5_bigip.bigip_as3_deploy`):

```yaml
      rescue:
        - name: "[RESCUE] DEBUG: Deploy error"
          debug:
            msg:
              - "RESULTS: {{ DEPLOY_RESULT }}"
          tags:
            - deploy-debug

        - name: "[RESCUE]: Deploy error"
          debug:
            msg:
              - "status:  {{ DEPLOY_RESULT.status }}"
              - "msg:     {{ DEPLOY_RESULT.msg }}"
              - "results: {{ DEPLOY_RESULT.json }}"
          tags:
            - deploy-debug
            - deploy
```

for "raw" access to device (`ansible.builtin.uri` module), you need authenticate with authentication token, not with user/pass:

```yaml
## 02 Authentication
    - block:
        - name: "{{pb_prfx}}-02-01: Get auth token"
          ansible.builtin.uri:
            url: "https://{{ bigip_host }}:{{ provider.server_port }}/mgmt/shared/authn/login"
            method: POST
            body: '{"username": "{{provider.user}}", "password": "{{provider.password}}", "loginProviderName": "tmos" }'
            body_format: json
            status_code: [200]
            timeout: 20
            return_content: true
            validate_certs: "{{ provider.validate_certs }}"
          register: AUTH_RESULT
          failed_when: AUTH_RESULT.status != 200
          check_mode: no

        - name: "{{pb_prfx}}-02-02: Auth token"
          debug:
            msg:
              - "token:  {{ AUTH_RESULT.json.token.token }}"

        - name: "{{pb_prfx}}-02-03: Set auth timeout to 5 min"
          ansible.builtin.uri:
            url: "https://{{ bigip_host }}:{{ provider.server_port }}/mgmt/shared/authz/tokens/{{AUTH_RESULT.json.token.token}}"
            method: PATCH
            body: '{ "timeout":"300" }'
            body_format: json
            headers:
              X-F5-Auth-Token: "{{ AUTH_RESULT.json.token.token }}"
            status_code: [200]
            timeout: 20
            return_content: true
            validate_certs: "{{ provider.validate_certs }}"
          check_mode: no

      when:
        - active_member is defined
        - active_member == true

      rescue:
        - name: "ERROR: Authentication fail"
          debug:
            msg:
              - "status:  {{ AUTH_RESULT.status }}"
              - "results: {{ AUTH_RESULT.json }}"

      tags:
        - auth
        - deploy
        - deploy-debug
```

maybe helps
