### ISSUE TITLE
bigip_sslo_config_topology issue - failed to resolve reference property appId = f5-ssl-orchestrator-tls

### ISSUE THREAD

**Issue by kevingstewart** [F5Networks/f5-ansible-bigip#37]
##### COMPONENT NAME
bigip_sslo_config_topology

##### ANSIBLE VERSION
```
ansible [core 2.12.5]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.10 (default, Mar 15 2022, 12:22:08) [GCC 9.4.0]
  jinja version = 3.1.2
  libyaml = True
```

##### BIGIP VERSION
```
Sys::Version
Main Package
  Product     BIG-IP
  Version     16.1.3.2
  Build       0.0.4
  Edition     Point Release 2
  Date        Wed Sep 14 08:12:07 PDT 2022
```

##### SSL ORCHESTRATOR VERSION
```
9.3.41
```

##### CONFIGURATION
No specific system/ansible configuration changes

##### OS / ENVIRONMENT
```
Ubuntu 20.04
Python 3.8.10
```

##### SUMMARY
On deploy of bigip_sslo_config_topology, the following fatal error is reported:
```
fatal: [172.16.1.83]: FAILED! => {"changed": false, "msg": "CREATE operation error: 8eac8010-3857-4762-a74c-e57e69a70579 : [OrchestratorConfigProcessor] Deployment failed for Error: [BaseHAConfigProcessor (TopologyBaseHAConfigProcessor)] Error: Failed to resolve reference property appId = f5-ssl-orchestrator-tls, propertyValue: l"}
```

- This issue is also reported here: https://github.com/f5devcentral/sslo-cloud-templates/issues/2
- The issue is due to shift from string to array value for sslSettingsReference in SSLO 9.1: https://docs.f5net.com/display/~dxie/SSLO+7.x+8.x+9.x+API+documentation

##### STEPS TO REPRODUCE
```
---
# Reference: https://clouddocs.f5.com/products/orchestration/ansible/devel/f5_bigip/modules_2_0/bigip_sslo_config_topology_module.html#bigip-sslo-config-topology-module-2

- name: Create SSLO Outbound L3 Topology Configuration
  hosts: all
  gather_facts: False

  collections:
    - f5networks.f5_bigip
  connection: httpapi

  vars:
    #ansible_host: "172.16.1.83"
    ansible_httpapi_port: 443
    ansible_user: "admin"
    ansible_httpapi_password: "admin"
    ansible_network_os: f5networks.f5_bigip.bigip
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no

  tasks:
    ## Topology
    - name: Create an SSLO Outbound L3 Topology
      bigip_sslo_config_topology:
        name: "demo_out_L3"
        state: "present"
        topology_type: "outbound_l3"
        ssl_settings: "sslconfig"
        security_policy: "sslopolicy"
        vlans:
        - "/Common/client-vlan"
        snat: "automap"
        gateway: "iplist"
        gateway_list:
        - ip: "172.16.0.1"
```
