### ISSUE TITLE
bigip_sslo_service_layer2 issue - unable to deploy an inline L2 service

### ISSUE THREAD

**Issue by kevingstewart** [F5Networks/f5-ansible-bigip#40]
##### COMPONENT NAME
bigip_sslo_service_layer2

##### ANSIBLE VERSION
```
ansible [core 2.12.5]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.10 (default, Mar 15 2022, 12:22:08) [GCC 9.4.0]
  jinja version = 3.1.2
  libyaml = True
```

##### BIGIP VERSION
```
Sys::Version
Main Package
  Product     BIG-IP
  Version     16.1.3.2
  Build       0.0.4
  Edition     Point Release 2
  Date        Wed Sep 14 08:12:07 PDT 2022
```

##### SSL ORCHESTRATOR VERSION
```
9.3.41
```

##### CONFIGURATION
No specific system/ansible configuration changes

##### OS / ENVIRONMENT
```
Ubuntu 20.04
Python 3.8.10
```

##### SUMMARY
Fatal error when trying to configure an inline L2 service
```
fatal: [172.16.1.83]: FAILED! => {"changed": false, "module_stderr": "'dict object' has no attribute 'service_subnet'", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error"}
```

##### STEPS TO REPRODUCE
```
---
# Reference: https://clouddocs.f5.com/products/orchestration/ansible/devel/f5_bigip/modules_2_0/bigip_sslo_service_layer2_module.html#bigip-sslo-service-layer2-module-2

- name: Create SSLO Inline L2 Service Configuration
  hosts: all
  gather_facts: False

  collections:
    - f5networks.f5_bigip
  connection: httpapi

  vars:
    #ansible_host: "172.16.1.83"
    ansible_httpapi_port: 443
    ansible_user: "admin"
    ansible_httpapi_password: "admin"
    ansible_network_os: f5networks.f5_bigip.bigip
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no

  tasks:
    ## Inline L2 service
    - name: Create an SSLO L2 service
      bigip_sslo_service_layer2:
        name: "FEYE"
        devices:
          - name: "FEYE1"
            ratio: 1
            interface_in: "1.4"
            interface_out: "1.5"
        port_remap: 8080
```
