### ISSUE TITLE
http proxy service fails with "Requested VLAN member (1) is not valid"

### ISSUE THREAD

**Issue by bradotlin** [F5Networks/f5-ansible-bigip#57]
##### COMPONENT NAME
```
bigip_sslo_service_http
```

##### ANSIBLE VERSION

```
core 2.12.5
```
##### BIGIP VERSION

```
16.1.3.1
```

##### SSL ORCHESTRATOR VERSION
```
9.3.41
```
##### OS / ENVIRONMENT

```
Ubuntu 20.04
Python 3.8.10
```

##### SUMMARY

```
While attempting to run the below playbook to create an http proxy on SSLO 9.3.4.1, I am met with a VLAN error. Interface 1.3 is not in use, nor are the 30 and 40 VLAN tags.
```
##### STEPS TO REPRODUCE

```
---
  
- name: Create SSLO service(s)
  hosts: all
  gather_facts: False
  connection: httpapi

  collections:
    - f5networks.f5_bigip
  vars:
    ansible_host: "10.0.10.146"
    ansible_httpapi_port: 443
    ansible_user: "admin"
    ansible_httpapi_password: "admin"
    ansible_network_os: f5networks.f5_bigip.bigip
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no
  tasks:
    - name: SSLO HTTP service
      bigip_sslo_service_http:
        name: "http"
        proxy_type: "explicit"
        devices_to:
          interface: "1.3"
          tag: 30
          self_ip: "198.19.96.7"
          netmask: "255.255.255.128"
        devices_from:
          interface: "1.3"
          tag: 40
          self_ip: "198.19.96.245"
          netmask: "255.255.255.128"
        devices:
          - ip: "198.19.96.30%0"
            port: 3128

```

##### ACTUAL RESULTS

```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "CREATE operation error: 0633f77e-2a1f-49dc-ae4c-73098a3e50e8 : [OrchestratorConfigProcessor] Deployment failed for Error: [HAAwareICRDeployProcessor] Error: transaction failed:01070256:3: Requested VLAN member (1) is not valid"}
```
