### ISSUE TITLE
bigip_sslo_service_http cannot create a service with an existing self-ip

### ISSUE THREAD

**Issue by megamattzilla** [F5Networks/f5-ansible-bigip#63]
##### COMPONENT NAME
bigip_sslo_service_http

##### ANSIBLE VERSION

```
ansible [core 2.12.2]
  config file = None
  configured module search path = ['/home/azureuser/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/azureuser/python3.8-ansible/lib/python3.8/site-packages/ansible
  ansible collection location = /home/azureuser/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/azureuser/python3.8-ansible/bin/ansible
  python version = 3.8.5 (default, Jan 27 2021, 15:41:15) [GCC 9.3.0]
  jinja version = 3.0.3
  libyaml = True
```
##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     16.1.3.3
  Build       0.0.3
  Edition     Point Release 3
  Date        Thu Dec 22 12:07:59 PST 2022
```
##### OS / ENVIRONMENT

Ubuntu 20.04.3

##### SUMMARY

bigip_sslo_service_http module cannot create a service when the referenced self_IP already exists on Big-IP. This is a valid configuration when using the SSLO user interface- you can select an already created self-IP. It seems the ansible module only supports creating a self-IP- it doesnt check if the self-IP already exists. 

##### STEPS TO REPRODUCE

```
  tasks:
    - name: Create a HTTP service
      bigip_sslo_service_http:
        name: "proxy1a"
        devices_to:
            vlan: "/Common/serviceChain1_in"
            self_ip: "172.23.3.4"
            netmask: "255.255.255.240"
        devices_from:
            vlan: "/Common/serviceChain1_out"
            self_ip: "172.23.3.17"
            netmask: "255.255.255.240"
        devices:
          - ip: "172.23.3.10"
        snat: none
        proxy_type: "explicit"
        auth_offload: false
        ip_family: "ipv4"
        service_down_action: "ignore"
```

##### EXPECTED RESULTS

Service is created successfully using the existing self_ip on Big-IP. 

##### ACTUAL RESULTS

```
task fails with error:
    "msg": "CREATE operation error: e06dc45b-317c-423a-a5e5-7e9e197c1734 : [OrchestratorConfigProcessor] Deployment failed for Error: [HAAwareICRDeployProcessor] Error: transaction failed:0107176c:3: Invalid self IP, the IP address 172.23.3.4 already exists."
```
