### ISSUE TITLE
Cannot create SSLO HTTP service proxy_type as Transparent with existing self IP

### ISSUE THREAD

**Issue by imohmmad** [F5Networks/f5-ansible-bigip#82]
COMPONENT NAME
bigip_sslo_service_http

Environment
ANSIBLE VERSION
ansible [core 2.16.2]
config file = /python-env/POD-ONBOARDING/ansible.cfg
configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = /python-env/ansible-9.1.0/lib/python3.11/site-packages/ansible
ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
executable location = /python-env/ansible-9.1.0/bin/ansible
python version = 3.11.4 (main, Dec 7 2023, 15:43:41) [GCC 12.3.0] (/python-env/ansible-9.1.0/bin/python3)
jinja version = 3.1.3
libyaml = True

BIGIP VERSION
Sys::Version
Main Package
Product BIG-IP
Version 17.1.1.1
Build 0.68.2

CONFIGURATION

OS / ENVIRONMENT
Ubuntu 20.04.3

SUMMARY
unable to create SSLO http service with proxy_type transparent while utilizing existing self_ip.

STEPS TO REPRODUCE
Create the following SSLO http service
    - name: Create Explicit HTTP service
      bigip_sslo_service_http:
        name: "HTTP-TRANSPARENT"
        proxy_type: "transparent"
        service_down_action: "ignore"
        auto_manage: false
        use_exist_selfip: true
        snat: "none"
        ip_family: "ipv4"
        devices_to:
          vlan: "/Common/TO_FE"
          self_ip: 10.10.1.1
          netmask: 255.255.255.0
        devices_from:
          vlan: "/Common/FROM_FE"
          self_ip: 10.10.2.2		
          netmask: 255.255.255.0
        devices:
          - ip: "10.10.1.2"

##### EXPECTED RESULTS
should be able to create http service with proxy type as transparent

##### ACTUAL RESULTS
   "msg": "CREATE operation error: a04ed767-cdec-4516-859e-8b1a8f001985 : [OrchestratorConfigProcessor] Deployment failed for Error: [BaseHAConfigProcessor (ServiceBaseHAConfigProcessor)] TypeError: Cannot read property 'lastIndexOf' of undefined"
}

**Comment by pgouband** [comment]
Hi,

Thanks for reporting. Added to the backlog and internal tracking ID for this request is: INFRAANO-1535.

**Comment by megamattzilla** [comment]
Hello! 

Is there an ETA for this fix? 

Thanks!

**Comment by prateekramani** [comment]
Hi @megamattzilla,
I attempted to reproduce it on my end, but unfortunately, I was unable to do so.
Could you please try running it on the latest build? The only action I took was to create the VLAN and self IP manually through the UI and it worked for me.

**Comment by megamattzilla** [comment]
I retested today on latest ansible version and bigip modules and I can still recreate the error:

Error:
```
TASK [Create Transparent HTTP service] **************************************************************************************************
fatal: [192.168.1.102]: FAILED! => {"changed": false, "msg": "CREATE operation error: bc5ffa65-faa6-4085-b2d4-e4ade90c3367 : [OrchestratorConfigProcessor] Deployment failed for Error: [BaseHAConfigProcessor (ServiceBaseHAConfigProcessor)] TypeError: Cannot read property 'lastIndexOf' of undefined"}
```


Playbook
```
- name: Create HTTP service
  hosts: "sslo17"
  connection: httpapi
  gather_facts: false
  any_errors_fatal: true


  tasks:

      - name: Test Module
        f5networks.f5_bigip.bigip_sslo_service_http:
          name: "proxy1a"
          state: "absent"

      - name: Create Transparent HTTP service
        f5networks.f5_bigip.bigip_sslo_service_http:
          name: "HTTP-TRANSPARENT"
          proxy_type: "transparent"
          service_down_action: "ignore"
          auto_manage: false
          use_exist_selfip: true
          snat: "none"
          ip_family: "ipv4"
          devices_to:
            vlan: "/Common/Internal1"
            self_ip: 10.10.1.1
            netmask: 255.255.255.0
          devices_from:
            vlan: "/Common/Internal2"
            self_ip: 10.10.2.2
            netmask: 255.255.255.0
          devices:
          - ip: "10.10.1.2"
```

Ansible version:
```
ansible-playbook --version                                     
ansible-playbook [core 2.17.2]
  config file = /Documents/GitHub/local-ansible/ansible.cfg
  configured module search path = ['/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /.pyenv/versions/3.10.14/envs/myenv/lib/python3.10/site-packages/ansible
  ansible collection location = /.ansible/collections:/usr/share/ansible/collections
  executable location = /.pyenv/versions/myenv/bin/ansible-playbook
  python version = 3.10.14 (main, Aug  5 2024, 09:03:11) [Clang 15.0.0 (clang-1500.3.9.4)] (/.pyenv/versions/3.10.14/envs/myenv/bin/python)
  jinja version = 3.1.4
  libyaml = True
  ```
