### ISSUE TITLE
declaration without class AS3 interpreted as Per-Application Deployment

### ISSUE THREAD

**Issue by simonkowallik** [F5Networks/f5-ansible-bigip#88]
##### COMPONENT NAME

`f5networks.f5_bigip.bigip_as3_deploy`

##### ANSIBLE VERSION

```
ansible [core 2.18.1]
  config file = /mnt/c/Users/C5272714/Workspace/s3-waf-btp-cc/ansible/ansible.cfg
  configured module search path = ['/mnt/c/Users/C5272714/Workspace/s3-waf-btp-cc/ansible/library']
  ansible python module location = /mnt/c/Users/C5272714/Workspace/s3-waf-btp-cc/ansible/.venv/lib/python3.12/site-packages/ansible
  ansible collection location = /mnt/c/Users/C5272714/Workspace/s3-waf-btp-cc/ansible/collections
  executable location = /mnt/c/Users/C5272714/Workspace/s3-waf-btp-cc/ansible/.venv/bin/ansible
  python version = 3.12.3 (main, Jan 17 2025, 18:03:48) [GCC 13.3.0] (/mnt/c/Users/C5272714/Workspace/s3-waf-btp-cc/ansible/.venv/bin/python)
  jinja version = 3.1.5
  libyaml = True
```
##### BIGIP VERSION

```
17.1.2.1

AS3 3.53.0
```
##### STEPS TO REPRODUCE

```yaml
    - name: Install AS3 Declaration
      f5networks.f5_bigip.bigip_as3_deploy:
        controls:
        # https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/declarations/http-services.html#using-a-local-traffic-policy-to-forward-http-requests
        content: |-
          {
            "class": "ADC",
            "schemaVersion": "3.2.0",
            "id": "ltm_policy",
            "label": "",
            "remark": "Simple HTTP application with LTM policy",
            "Sample_http_08": {
              "class": "Tenant",
              "A1": {
                "class": "Application",
                "service": {
                  "class": "Service_HTTP",
                  "virtualAddresses": [
                    "10.0.1.10"
                  ],
                  "policyEndpoint": "forward_policy"
                },
                "web_pool": {
                  "class": "Pool",
                  "monitors": [
                    "http"
                  ],
                  "members": [{
                    "servicePort": 80,
                    "serverAddresses": [
                      "192.0.2.10",
                      "192.0.2.11"
                    ]
                  }]
                },
                "forward_policy": {
                  "class": "Endpoint_Policy",
                  "rules": [{
                    "name": "forward_to_pool",
                    "conditions": [{
                      "type": "httpUri",
                      "path": {
                        "operand": "contains",
                        "values": ["example.com"]
                      }
                    }],
                    "actions": [{
                      "type": "forward",
                      "event": "request",
                      "select": {
                        "pool": {
                          "use": "web_pool"
                        }
                      }
                    }]
                  }]
                }
              }
            }
          }
```

##### EXPECTED RESULTS

Implements AS3 declaration successfully.

##### ACTUAL RESULTS

```
msg: tenant parameter is mandatory for Per-Application Deployment
```

`bigip_as3_deploy` seems to assume any declaration that does not use `"class": "AS3"` is supposed to be a Per Application Declaration.
